-- for help: \?
-- list databases: \l
-- connect to a new database: \c
-- list all tables: \d
-- list a table: \d nameoftable
-- Create database: CREATE DATABASE practice;
-- DATABASE_URL=postgres://postgres:randomPassword@localhost:5432/cryptoProject